# ---------------------------------------------------------------------
# New Relic Python Agent configuration file.
#
# Secrets/per-environment values (license key, app name) are pulled from
# the process environment via the %(env.VAR)s interpolation the agent's
# config parser supports — set NEW_RELIC_LICENSE_KEY / NEW_RELIC_APP_NAME
# as real env vars (Railway service settings, or .env locally), never here.
# This is a trimmed version of the `newrelic-admin generate-config`
# template; anything not listed below uses the agent's documented default.
# ---------------------------------------------------------------------

[newrelic]
license_key = %(env.NEW_RELIC_LICENSE_KEY)s
app_name = %(env.NEW_RELIC_APP_NAME)s
monitor_mode = true
log_file = stdout
log_level = info
high_security = false

distributed_tracing.enabled = true

error_collector.enabled = true
error_collector.ignore_status_codes = 404

transaction_tracer.enabled = true
transaction_tracer.transaction_threshold = apdex_f
transaction_tracer.record_sql = obfuscated
