# Generated by Django 6.1 on 2026-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackevent',
            options={},
        ),
        migrations.AlterField(
            model_name='slackevent',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='slackevent',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='slackevent',
            name='team_id',
            field=models.CharField(max_length=32),
        ),
    ]
