# Generated by Django 6.1 on 2026-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_alter_slackevent_options_alter_slackevent_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slack_user_id', models.CharField(max_length=32, unique=True)),
                ('slack_user_token', models.CharField(max_length=256)),
                ('cma_memory_id', models.CharField(blank=True, default='', max_length=128)),
                ('cma_instructions_memory_id', models.CharField(blank=True, default='', max_length=128)),
                ('asana_workspace_gid', models.CharField(max_length=32)),
                ('asana_project_gids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
