# Generated by Django 6.1 on 2026-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='asana_workspace_gid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
