# Generated by Django 6.1 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_alter_teams_asana_workspace_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='cma_agent_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
