"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sfbxi#3vi!fhuyf8xwb$3y@c9t#b+oc8%=3-7+@3)&@ozq+%23'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '.ngrok-free.app', '.ngrok-free.dev'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'slack',
    'agent',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Slack
# https://api.slack.com/authentication/verifying-requests-from-slack

SLACK_SIGNING_SECRET = env('SLACK_SIGNING_SECRET', default='')

# Bot token for calling the Slack Web API (e.g. from Bolt listeners via `say()`/`client`).
# Left unset (None, not '') until a real token is configured — Bolt only calls Slack's
# auth.test to verify the token at startup when one is actually present.
SLACK_BOT_TOKEN = env('SLACK_BOT_TOKEN', default=None)

# User token (xoxp). Required only by the agent's search tool: search.messages has no
# bot-token equivalent, so it is the one Slack read that cannot use SLACK_BOT_TOKEN.
SLACK_USER_TOKEN = env('SLACK_USER_TOKEN', default='')


# Asana
# https://developers.asana.com/docs/personal-access-token

# Personal Access Token used by AsanaClientService to call Asana's REST API directly
# from Django (custom tools, not MCP) — real network access, unlike the CMA sandbox's
# skill scripts, which have no egress at all.
ASANA_ACCESS_TOKEN = env('ASANA_ACCESS_TOKEN', default='')


# Agent access policy
#
# Channel whitelisting is enforced via constants.WHITELISTED_CHANNELS (read by
# AgentToolGateService and SlackChannelSearchService) rather than settings/env
# — one list, in code, not duplicated here.

# MCP tools the agent may call, mapped to the input field carrying the channel ID.
# None means the tool takes no channel and needs no channel check. Anything absent from
# this mapping is denied, so the tool names must match the deployed MCP server exactly —
# these match korotovsky/slack-mcp-server (github.com/korotovsky/slack-mcp-server).
#
# Deliberately excluded: `channels_list`. Django can only approve or refuse an MCP call,
# never filter its response, so a tool that enumerates channels would leak the names of
# channels outside this whitelist even if every read of their content is denied. Also
# excluded: `conversations_search_messages`, this server's own search tool — search is
# served by the custom search tool instead, because channel scope lives inside its
# free-text query and a binary allow/deny gate cannot narrow it. Restrict both of these
# server-side too, via that server's SLACK_MCP_ENABLED_TOOLS, as defense in depth.
AGENT_MCP_TOOL_ALLOWLIST = {
    'conversations_history': 'channel_id',
    'conversations_replies': 'channel_id',
    'users_search': None,
}


# Claude Managed Agents
# https://platform.claude.com/docs/en/managed-agents/overview

ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')

# Created once with the `ant` CLI from cma/agent.yaml and cma/environment.yaml.
CMA_AGENT_ID = env('CMA_AGENT_ID', default='')
CMA_ENVIRONMENT_ID = env('CMA_ENVIRONMENT_ID', default='')

# Holds the static bearer credential authenticating CMA to the self-hosted Slack MCP
# server. Without it that server is reachable by anyone who learns its URL.
CMA_VAULT_ID = env('CMA_VAULT_ID', default='')

# Hard per-session spend cap, in US cents, so a runaway run cannot bill without bound.
CMA_SESSION_BUDGET_CENTS = env.int('CMA_SESSION_BUDGET_CENTS', default=200)
