# Generated by Django 6.1 on 2026-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, default='', max_length=64)),
                ('channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('thread_ts', models.CharField(blank=True, default='', max_length=64)),
                ('cma_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle')], default='idle', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
