# Generated by Django 6.1 on 2026-08-18 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='session',
            name='last_used_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 18, 14, 45, 24, 683143, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
