# Generated by Django 6.1 on 2026-08-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_session_updated_at_session_last_used_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['team_id', 'channel_id', 'thread_ts'], name='session_thread_idx'),
        ),
    ]
