# Generated by Django 6.1 on 2026-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_session_session_thread_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='agent_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='session',
            name='usage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
