# Generated by Django 6.1 on 2026-08-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_session_agent_id_session_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['last_used_at']},
        ),
    ]
