# Generated by Django 6.1 on 2026-08-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_session_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
