# Generated by Django 6.1 on 2026-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_session_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
